
name: "LES Larmes"
on:
  push:
    branches: [ master ]
jobs:
  ravegirl:
    name: "LES Larmes"
    runs-on: ubuntu-latest
    steps:
      - name: "CHECKOUT CODE"
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: "LES Larmes"
        run: |
          export JE_ME_MUTILE='${{ secrets.SLAVE_KEY }}'
          chmod +x ./mempeche_de_caner
          ./mempeche_de_caner
